### ISSUE TITLE
Semver breaking change in v0.2.2

### ISSUE THREAD

**Issue by tarcieri** [aahancoc/tree_magic#18]
First, thanks for this crate. It's the nicest MIME type detector I've found in pure Rust.

I'm using it as a library, and the v0.2.2 release made a breaking change to the API, namely `tree_magic::from_filepath` now returns an `Option`.

I've gone ahead and changed my crate's version requirement to be `= 0.2.1` until I can update it, but in the future it'd be helpful if changes like this could be accompanied by a minor version bump.

**Comment by aahancoc** [comment]
Whoops, I apologize about that. I'll try and fix that and make a 0.2.3 release.

**Comment by aahancoc** [comment]
The issue was that I had completely forgotten that I had started work on `master` that deviated from 0.2.x's API.

**Comment by aahancoc** [comment]
Version 0.2.2 has been yanked. Closing this issue.

**Comment by tarcieri** [comment]
Thank you! That version worked like a charm.
