### ISSUE TITLE
`Option::unwrap()` on a `None` value for non regular files

### ISSUE THREAD

**Issue by kamiyaa** [aahancoc/tree_magic#9]
Happens when `tree_magic::from_filepath(path)` is called on non regular files such as fifo, character, block files.

Might be out of scope of this project, but I'll submit this anyways.

**Comment by BrainBlasted** [comment]
Perhaps the error could be propagated? We're currently hitting a crash with this in https://gitlab.gnome.org/GNOME/fractal/issues/37

**Comment by kamiyaa** [comment]
Fixed via 9bc1f46eeda7985aa06ecb1b4f0dc8c306706f8c
